### ISSUE TITLE
[Issue] cant install

### ISSUE THREAD

**Issue by pizzav-xyz** [zer0yu/ghtracker#3]
**Describe the bug**
when i run install command it doesnt work

**ghtracker version**
Include the version of ghtracker you are using, `ghtracker -version`

**Complete command you used to reproduce this**

**Screenshots**
Add screenshots of the error for a better context.
![image](https://github.com/user-attachments/assets/90a45776-01cf-4194-9035-d34564eca7f8)

**Comment by zer0yu** [comment]
You need to add golang's bin directory to the environment variable.
